backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "articles"
    label: "Статьи"
    folder: "src/pages"
    create: true
    slug: "{{category}}/{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Категория"
        name: "category"
        widget: "select"
        default: [{ label: "Новости", value: "news" }]
        options:
          - { label: "Новости", value: "news" }
          - { label: "Кулинария", value: "cooking" }
          - { label: "Праздники", value: "holidays" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Фото (превью)", name: "featuredimage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Теги", name: "tags", widget: "list", required: false}
